name: screenshots
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install dependencies
        run: npm install
      - name: Run local web server
        run: pm2 --name HelloWorldApp start npm -- start
      - name: Take screenshot
        run: npm run screenshot
